export type Item = {
    id: string,
    url_name: string,
    name: string,
    wiki_link: string,
    component: boolean,
    set: boolean,
    prime: boolean,
    blueprint: boolean,
    syndicate: boolean,
    primary_weapon: boolean,
    secondary_weapon: boolean,
    warframe: boolean,
    melee_weapon: boolean,
    mod: boolean,
    arcane: boolean,
    archwing: boolean,
    ducats: number,
    skin: boolean,
    lens: boolean,
    riven: boolean,
    misc: boolean,
    last_scrape: string | null,
    number_of_scrapes: number,
}